apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notification-service-config
data:
  POSTGRES_URI: "postgresql://user:password@notification-service-db-0.notification-service-db-svc.default.svc.cluster.local:5432/notification_db"
