apiVersion: v1
kind: Service
metadata:
  name: habit-service-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: habit-service
