apiVersion: v1
kind: Service
metadata:
  name: journal-service-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: journal-service
