apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-auth-service-config
            - secretRef:
                name: {{ .Release.Name }}-auth-service-secret
